apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apicurio-designer
  - cert-manager
  - developer-hub
  - hawtio
  - kaoto
  - keycloak
  - microcks
  - openshift-pipelines